CREATE TABLE IF NOT EXISTS users (
 id SERIAL PRIMARY KEY,
 username VARCHAR(50) UNIQUE NOT NULL,
 email VARCHAR(120) UNIQUE NOT NULL,
 password TEXT NOT NULL,
 avatar TEXT DEFAULT '',
 bio TEXT DEFAULT '',
 created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS posts (
 id SERIAL PRIMARY KEY,
 user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 image TEXT NOT NULL,
 caption TEXT DEFAULT '',
 created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS likes (
 id SERIAL PRIMARY KEY,
 user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE,
 UNIQUE(user_id, post_id)
);

CREATE TABLE IF NOT EXISTS follows (
 id SERIAL PRIMARY KEY,
 follower_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 following_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 UNIQUE(follower_id, following_id)
);

CREATE TABLE IF NOT EXISTS messages (
 id SERIAL PRIMARY KEY,
 sender_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 receiver_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 text TEXT NOT NULL,
 created_at TIMESTAMP DEFAULT NOW()
);
